### ISSUE TITLE
Local wallet Mints using 20K for Remote Master Node

### ISSUE THREAD

**Issue by DaZuru** [cevap/ion#4] opened 2018-03-26 19:29 UTC
### Describe the issue
Running remote MN on Ubuntu 17.10. Running local wallet 3.0.4 on Windows 10. Used setup guide and MN was running for around five hours. Unlocked local wallet to stake coins over the 20K which were supposed to be locked. Took a few minutes and the 20K Minted and the MN went from Enabled to Missing.

#### If so, please list the steps to reproduce below:
1. Get remote MN working.
2. Unlock local wallet for staking only.
3. Mints on 20K and disables MN.

### Expected behavior
Local wallet should have locked the 20K and staked the remainder.

### Actual behavior
Mints on 20K.

### Screenshots.
N/A

### What version of Ion Core are you using?
Local 3.0.4, Remote 3.0.3

### Machine specs:
- OS: Remote Ubuntu 17.10, Local Windows 10
- CPU: Remote running under ESXi, Local AMD FX-8350
- RAM: Remote 2GB, Local 32GB
- Disk size: Remote 1TB VMDK, 4TB SATA
- Disk Type (HD/SDD): VMDK/SATA

**Comment by FornaxA** [comment] 2018-03-26 19:47
Can you post your anonymized ioncoin.conf files and masternode.conf?

**Comment by cevap** [comment] 2018-03-26 20:03
Thanks for submitting the issue

as @FornaxA asked, please show us your configs without keys, username and password. Additionally, if you look up in your log and find those lines where it happened, it would be more clearer what happened.

if you staked, did your amount split and/or is your masternode still active or do you get txid error when activating it? Try activating with this command: `startmasternode alias 0 YourMNAlias`.

When you post your configs please check twice to **remove rpcusername and rpcpassworde** as well as **masternode private keys** (_those are hopefully not from your wallet but generated by masternode genkey_)

**Comment by DaZuru** [comment] 2018-03-26 22:02
Attached are heavily redacted configs in a PGP file with fornaxA's public key. Seems like I redacted quite a bit!  It split in two. I will check the log file. I went ahead and created new settings and have it running again. Hope that doesn't hurt the troubleshooting.
[RedactedPGPConfigs.txt](https://github.com/cevap/ion/files/1849689/RedactedPGPConfigs.txt)

**Comment by FornaxA** [comment] 2018-03-30 08:40
@DaZuru : mnconflock can be removed from your ioncoin.conf.

The log file shows the minting tx.. Can you go back to when you started the wallet, and find the section that looks like this:

```
2018-03-30 08:37:48 init message: Loading masternode payment cache...
2018-03-30 08:37:48 Locking Masternodes:
2018-03-30 08:37:48   <TXHASH> <VOUT>
```
(Where <TXHASH> and <VOUT> refer to the tx id and vout that are defined in your masternode.conf)

**Comment by cevap** [comment] 2018-03-30 11:31
I can not decode, you seem not have added my public key to the encryption.

@DaZuru this is how it looks if you run it together with masternode.conf
```
2018-03-30 06:31:10 init message: Loading masternode cache...
2018-03-30 06:31:10 init message: Loading budget cache...
2018-03-30 06:31:10 init message: Loading masternode payment cache...
2018-03-30 06:31:10 Locking Masternodes:
2018-03-30 06:31:10   9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 4
2018-03-30 06:31:10   9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 0
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 1
2018-03-30 06:31:10   9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 1
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 3
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 4
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 6
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 7
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 8
2018-03-30 06:31:10   9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 2
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 10
2018-03-30 06:31:10   4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 11
2018-03-30 06:31:10   2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7 0
2018-03-30 06:31:10   6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx3 1
2018-03-30 06:31:10   bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 0
2018-03-30 06:31:10   bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 1
2018-03-30 06:31:10   9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc 0
2018-03-30 06:31:10   bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe 4
2018-03-30 06:31:10   0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxa 1
2018-03-30 06:31:10   8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb 0
2018-03-30 06:31:10 fLiteMode 0
```
mnconflock is not required and was actually not in our guide. 

Beside your config, you might start it also wrongly. You can reffer to console help which has all required information, here is as example `--help masternode`
```
masternode "command"...

Set of commands to execute masternode related actions
This command is depreciated, please see individual command documentation for future reference


Arguments:
1. "command"        (string or set of strings, required) The command to execute

Available commands:
  count        - Print count information of all known masternodes
  current      - Print info on current masternode winner
  debug        - Print masternode status
  genkey       - Generate new masternodeprivkey
  outputs      - Print masternode compatible outputs
  start        - Start masternode configured in ioncoin.conf
  start-alias  - Start single masternode by assigned alias configured in masternode.conf
  start-<mode> - Start masternodes configured in masternode.conf (<mode>: 'all', 'missing', 'disabled')
  status       - Print masternode status information
  list         - Print list of all known masternodes (see masternodelist for more info)
  list-conf    - Print masternode.conf in JSON format
  winners      - Print list of masternode winners
```

If you txid is confirmed and unsplitted (like by stake), and your index is correct as well as port number and masternode's private key, then it will work.

Please supply your configs in plaintext (non excrypted) **without RPC password/username and private keys". I am quite sure that your configs are not correct.

**Comment by DaZuru** [comment] 2018-03-30 14:45
@FornaxA I started and stopped the wallet a few times. In the section where the mint occurred, there was no Locking Masternodes. My guess is that I didn't start the Masternode or have the masternode config in place before it minted. It minted five minutes after start. I could have been editing files and letting blocks catch up. I have already resent 20K to a new address and reconfigured the masternode with new data. It has been working but I have not enabled staking.

**Comment by FornaxA** [comment] 2018-03-30 19:03
@DaZuru : it should not be able to mint before everything was synchronized, but yeah, perhaps it was a freak occurrence or maybe related to editing config files/not saving files before starting the node/etc.

Either way: if it occurs again, please reopen this issue (I'm closing it now). And no need to apologize: thank you for opening the issue and taking the trouble to share your files!

**Closed by FornaxA** 2018-03-30 19:03 UTC
Labels: question
