### ISSUE TITLE
[BUG] cs_wallet locks not held when calling 'masternode outputs'

### ISSUE THREAD

**Issue by FornaxA** [cevap/ion#126] opened 2018-12-23 12:36 UTC
When giving the cli command `masternode outputs`, the client crashes due to locks on cs_wallet not being held.

**To Reproduce**
1. Compile a wallet with --enable-debug
2. Ensure you should have 20k masternode blocks in the wallet
3. With the cli, call `masternode outputs`
4. Result:
```
$ ion-cli -testnet=1 masternode outputs
Assertion failed: lock cs_wallet not held in wallet.cpp:3943; locks held:
error: couldn't connect to server
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Compiled from cevap/ion master commit a5d4c61ee7003f3b2e7338ca829d6167b86ee6d1

**Additional context**
The following locks are asserted but not set in SelectCoinsMasternode():
```
void CWallet::LockCoin(const COutPoint& output)
{
    AssertLockHeld(cs_wallet); // setLockedCoins
    setLockedCoins.insert(output);
}

void CWallet::UnlockCoin(const COutPoint& output)
{
    AssertLockHeld(cs_wallet); // setLockedCoins
    setLockedCoins.erase(output);
}
```

**Comment by cevap** [comment] 2018-12-23 14:35
I cant reproduce this bug, ubuntu bionic 18.04. Masternode outputs work as it is supposed to be used. I made the test only on main as testnet is unlaunched/noCoins.

Please test release binaries, I will compile in the evening master with "--enable-debug", to see if I can reproduce this bug

**Comment by cevap** [comment] 2018-12-23 14:38
2 downloads, one of them my, the other from @ckti , please test it https://github.com/cevap/ion/issues/125 and other binaries too, like I said, I cant reproduce it for now with release binaries.

**Comment by FornaxA** [comment] 2018-12-24 09:19
I tried with those gitian compiled binaries and that does not produce that error - which makes sense, because they are not compiled in debug mode. The assertion is only made in debug mode.
However, the issue remains: either the assertion isn't necessary, or the lock needs to be set before the assertion is made.

**Comment by cevap** [comment] 2018-12-24 13:12
I close this issue,  #127  , open please if not resolved

**Closed by cevap** 2018-12-24 13:12 UTC
Labels: Bug
